<?php

namespace MtgBundle\Repository;

use \Doctrine\ORM\EntityRepository as Repository;
/**
 * CardSetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CardSetRepository extends Repository
{
}
