<?php

namespace MtgBundle\Repository;

/**
 * CardFaceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CardFaceRepository extends \Doctrine\ORM\EntityRepository
{
}
