<?php

namespace MtgBundle\Repository;

/**
 * CardCollectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CardCollectionRepository extends \Doctrine\ORM\EntityRepository
{
}
