<?php

namespace MtgBundle\Repository;

/**
 * DeckCardsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeckCardsRepository extends \Doctrine\ORM\EntityRepository
{
}
