<?php

namespace MtgBundle\Repository;

/**
 * RulingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RulingRepository extends \Doctrine\ORM\EntityRepository
{
}
