fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

app:
    resource: '@MtgBundle/Controller/'
    type: annotation

home:
    path: /
    defaults:
        _controller: MtgBundle:Default:index

mtg:
    resource: "@MtgBundle/Controller/"
    type:     annotation
    prefix:   /
