<?php
namespace F1Bundle\Repository;

use Doctrine\ORM\EntityRepository;
use F1Bundle\Entity\Circuit;

/**
 * CircuitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CircuitRepository extends EntityRepository
{
    /**
     * @param $circuitId
     *
     * @return Circuit|object
     */
    public function getByCircuitId($circuitId)
    {
        return $this->findOneBy(['circuitId' => $circuitId]);
    }
}
