<?php

namespace F1Bundle\Repository;

use Doctrine\ORM\EntityRepository;
use F1Bundle\Entity\Driver;

/**
 * DriverRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DriverRepository extends EntityRepository
{
    /**
     * @param $code
     *
     * @return Driver|object
     */
    public function findOneByCode($code)
    {
        return $this->findOneBy(['code' => $code]);
    }
}
