<?php

namespace F1Bundle\Repository;

/**
 * LapResultRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LapResultRepository extends \Doctrine\ORM\EntityRepository
{
}
