<?php

namespace F1Bundle\Repository;

use Doctrine\ORM\EntityRepository;
use F1Bundle\Entity\Circuit;
use F1Bundle\Entity\Race;
use F1Bundle\Entity\Season;

/**
 * RaceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RaceRepository extends EntityRepository
{
    /**
     * @param Season $season
     * @param Circuit $circuit
     *
     * @return Race|object
     */
    public function getBySeasonAndCircuit($season, $circuit)
    {
        return $this->findOneBy(['season' => $season, 'circuit' => $circuit]);
    }

    /**
     * @param $season
     * @param $round
     *
     * @return null|Race
     */
    public function getBySeasonAndRound($season, $round)
    {
        return $this->findOneBy(['season' => $season, 'round' => $round]);
    }
}
