<?php

namespace F1Bundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RaceResultRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RaceResultRepository extends EntityRepository
{
    public function getResultsByRace($race)
    {
        return $this->findBy(['race' => $race]);
    }
}
