<?php

namespace F1Bundle\Repository;

use Doctrine\ORM\EntityRepository;
use F1Bundle\Entity\Season;

/**
 * SeasonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SeasonRepository extends EntityRepository
{
    /**
     * @param $season
     *
     * @return Season|object
     */
    public function getBySeason($season)
    {
        return $this->findOneBy(['season' => $season]);
    }
}
