services:
    mtg.card:
        class: 'MtgBundle\Service\MtgCardService'
        public: true
        arguments: [ "@doctrine.orm.entity_manager" ]

    mtg.set:
        class: 'MtgBundle\Service\MtgSetService'
        public: true
        arguments: [ "@doctrine.orm.entity_manager" ]

    mtg.collection:
        class: 'MtgBundle\Service\MtgCollectionService'
        public: true
        arguments: [ "@doctrine.orm.entity_manager", "@mtg.card"]

    mtg.extrainfo:
        class: 'MtgBundle\Service\MtgExtraLiveDataService'
        public: true
        arguments: [ "@doctrine.orm.entity_manager"]

    mtg.deck:
        class: 'MtgBundle\Service\MtgDeckService'
        public: true
        arguments: [ "@doctrine.orm.entity_manager"]

    mtg.symbol_extension:
        class: MtgBundle\Twig\MtgSymbolExtension
        tags:
            - { name: twig.extension }
        autowire: true
