services:
    _defaults:
        public: false
        autoconfigure: true
        autowire: true

    MtgBundle\Service\:
        resource: '../../Service/'
        autowire: true
        arguments: [ "@doctrine.orm.entity_manager"]

    MtgBundle\Controller\:
        resource: '../../Controller'
        #tags: ['controller.service_arguments']

    mtg.symbol_extension:
        class: MtgBundle\Twig\MtgSymbolExtension
        tags:
            - { name: twig.extension }
        autowire: true
